### ISSUE TITLE
accuracy is always 0 during training 

### ISSUE THREAD

**Issue by gaobaoding** [Microsoft/singleshotpose#82] opened 2019-04-11 06:00 UTC
Nope, I checked all my labeling and couldn't find what is not correct.

> Did you manage to solve the problem? I am also getting 0% accuracy as it seems:
> 
> 019-03-20 14:12:14 Number of test samples: 60
> tensor to cuda : 0.000999
> predict : 0.011994
> get_region_boxes : 0.015990
> eval : 0.035156
> total : 0.064140
> 2019-03-20 14:12:20 Mean corner error is 355.253784
> 2019-03-20 14:12:20 Acc using 5 px 2D Projection = 0.00%
> 2019-03-20 14:12:20 Acc using 0.0103 vx 3D Transformation = 0.00%
> 2019-03-20 14:12:20 Acc using 5 cm 5 degree metric = 0.00%
> 2019-03-20 14:12:20 Translation error: 18381.882744, angle error: 125.722093

_Originally posted by @s0972456 in https://github.com/Microsoft/singleshotpose/issues/65#issuecomment-475655889_

**Comment by btekin** [comment] 2019-04-11 06:56
Duplicate of #65, closing this and reopening #65.

**Closed by btekin** 2019-04-11 06:56 UTC
